# Generated by Django 4.1 on 2022-08-16 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('name', models.CharField(max_length=100, verbose_name='ルーム名')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('name', models.CharField(max_length=100, verbose_name='投稿者名')),
                ('ip', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('comment', models.TextField(verbose_name='原文コメント')),
                ('ja_comment', models.TextField(verbose_name='日本語コメント')),
                ('en_comment', models.TextField(verbose_name='英語コメント')),
                ('zh_comment', models.TextField(verbose_name='中国語コメント')),
                ('ko_comment', models.TextField(verbose_name='韓国語コメント')),
                ('de_comment', models.TextField(verbose_name='ドイツ語コメント')),
                ('fr_comment', models.TextField(verbose_name='フランス語コメント')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room', verbose_name='ルーム名')),
            ],
        ),
    ]
